### ISSUE TITLE
Secret passage

### ISSUE THREAD

**Issue by PazitiF** [yznpku/LabCompass#7]
Compass layout don't show secret passage way.
![3](https://user-images.githubusercontent.com/34467198/34649114-82ee5ae8-f3b9-11e7-8d04-95e0963b3396.png)

**Comment by FiftyCaliber** [comment]
Just found this LabCompass and using it for the first time now actually, and noticed this same issue with today's layout. Since I assume mistakes like this happen from time to time I would recommend adding an option for people to manually adjust their current position when it's incorrect due to going through a secret passage that doesn't exist according to the app.
